"""stock ticker info added fields

Revision ID: 2d462b6bccc
Revises: 36f6c0ac7db
Create Date: 2019-03-15 11:15:48.583874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d462b6bccc'
down_revision = '36f6c0ac7db'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ticker_info', sa.Column('data_present', sa.Boolean(), nullable=True))
    op.add_column('stock_ticker_info', sa.Column('newest_date', sa.DateTime(), nullable=True))
    op.add_column('stock_ticker_info', sa.Column('oldest_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_stock_ticker_info_data_present'), 'stock_ticker_info', ['data_present'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ticker_info_data_present'), table_name='stock_ticker_info')
    op.drop_column('stock_ticker_info', 'oldest_date')
    op.drop_column('stock_ticker_info', 'newest_date')
    op.drop_column('stock_ticker_info', 'data_present')
    ### end Alembic commands ###
