"""stock ticker info table

Revision ID: 36f6c0ac7db
Revises: c3e8bf162d
Create Date: 2019-03-15 11:04:46.819640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f6c0ac7db'
down_revision = 'c3e8bf162d'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_ticker_info',
    sa.Column('stock_ticker', sa.String(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('stock_ticker')
    )
    op.create_index(op.f('ix_stock_ticker_info_last_accessed'), 'stock_ticker_info', ['last_accessed'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ticker_info_last_accessed'), table_name='stock_ticker_info')
    op.drop_table('stock_ticker_info')
    ### end Alembic commands ###
