"""added number of entries

Revision ID: 58e1b4eaa0a
Revises: 2d462b6bccc
Create Date: 2019-03-17 17:06:32.951525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e1b4eaa0a'
down_revision = '2d462b6bccc'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ticker_info', sa.Column('number_of_entries', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_ticker_info', 'number_of_entries')
    ### end Alembic commands ###
