"""Historical Data Table

Revision ID: c3e8bf162d
Revises: 
Create Date: 2019-02-17 19:22:59.988482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e8bf162d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_daily_price',
    sa.Column('stock_ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('lowest_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('highest_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('stock_ticker', 'date')
    )
    op.create_index(op.f('ix_stock_daily_price_close_price'), 'stock_daily_price', ['close_price'], unique=False)
    op.create_index(op.f('ix_stock_daily_price_highest_price'), 'stock_daily_price', ['highest_price'], unique=False)
    op.create_index(op.f('ix_stock_daily_price_lowest_price'), 'stock_daily_price', ['lowest_price'], unique=False)
    op.create_index(op.f('ix_stock_daily_price_open_price'), 'stock_daily_price', ['open_price'], unique=False)
    op.create_index(op.f('ix_stock_daily_price_volume'), 'stock_daily_price', ['volume'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_daily_price_volume'), table_name='stock_daily_price')
    op.drop_index(op.f('ix_stock_daily_price_open_price'), table_name='stock_daily_price')
    op.drop_index(op.f('ix_stock_daily_price_lowest_price'), table_name='stock_daily_price')
    op.drop_index(op.f('ix_stock_daily_price_highest_price'), table_name='stock_daily_price')
    op.drop_index(op.f('ix_stock_daily_price_close_price'), table_name='stock_daily_price')
    op.drop_table('stock_daily_price')
    ### end Alembic commands ###
